[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "openai"
version = "1.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ChatGPT", "Vendor/OpenAI", "Area/AI", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
